name: Publish docs via GitHub Pages
# on:
#   push:
#     branches:
#       - old_doc

# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v1

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# NOTE: nav section is configured in .pages file in /docs using awesome-pages plugin.
on:
  push:
    branches:
      - old_doc
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
            fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mkdocs-open-in-new-tab
      - run: pip install mkdocs-glightbox
      - run: mkdocs gh-deploy --force --clean --verbose
